apiVersion: v1
kind: Service
metadata:
  name: matcher-service
  namespace: nimbusflow

  labels:
    app: matcher-service

spec:
  selector:
    app: matcher-service

  ports:
    - name: http
      port: 8000
      targetPort: 8000