apiVersion: v1
kind: Service
metadata:
  name: resume-service
  namespace: nimbusflow

  labels:
    app: resume-service

spec:
  selector:
    app: resume-service

  ports:
    - name: http
      port: 8081
      targetPort: 8081