apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: nimbusflow

spec:
  replicas: 1

  selector:
    matchLabels:
      app: discovery-server

  template:
    metadata:
      labels:
        app: discovery-server

    spec:
      containers:

        - name: discovery-server

          image: sapan18/discovery-server:v2

          ports:
            - containerPort: 8761

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761

            initialDelaySeconds: 60
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761

            initialDelaySeconds: 30
            periodSeconds: 10