apiVersion: v1
kind: Secret

metadata:
  name: nimbusflow-secret
  namespace: nimbusflow

type: Opaque

stringData:
  POSTGRES_USER: postgres

  POSTGRES_PASSWORD: postgres

  JWT_SECRET: mysecretkeymysecretkeymysecretkey