apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: nimbusflow

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:

        - name: api-gateway

          image: sapan18/api-gateway:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nimbusflow-secret
                  key: JWT_SECRET

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 60
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 30
            periodSeconds: 10