apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  namespace: nimbusflow

spec:
  replicas: 1

  selector:
    matchLabels:
      app: job-service

  template:
    metadata:
      labels:
        app: job-service

    spec:
      containers:

        - name: job-service

          image: sapan18/job-service:v2

          ports:
            - containerPort: 8082

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: nimbusflow-config
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nimbusflow-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nimbusflow-secret
                  key: POSTGRES_PASSWORD

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082

            initialDelaySeconds: 60
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082

            initialDelaySeconds: 30
            periodSeconds: 10