server.port=8761
spring.application.name=discovery-server

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# -----------------------------------
# Actuator Endpoints
# -----------------------------------
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# -----------------------------------
# Prometheus Metrics
# -----------------------------------
management.metrics.export.prometheus.enabled=true