name: NimbusFlow Backend CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build Backend
        run: mvn clean package -DskipTests

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # API Gateway
      - name: Build API Gateway Image
        run: |
          docker build -f api-gateway/Dockerfile -t sapan18/api-gateway:v1 .

      - name: Push API Gateway Image
        run: |
          docker push sapan18/api-gateway:v1

      # Auth Service
      - name: Build Auth Service Image
        run: |
          docker build -f auth-service/Dockerfile -t sapan18/auth-service:v1 .

      - name: Push Auth Service Image
        run: |
          docker push sapan18/auth-service:v1

      # Resume Service
      - name: Build Resume Service Image
        run: |
          docker build -f resume-service/Dockerfile -t sapan18/resume-service:v1 .

      - name: Push Resume Service Image
        run: |
          docker push sapan18/resume-service:v1

      # Job Service
      - name: Build Job Service Image
        run: |
          docker build -f job-service/Dockerfile -t sapan18/job-service:v1 .

      - name: Push Job Service Image
        run: |
          docker push sapan18/job-service:v1

      # Discovery Server
      - name: Build Discovery Server Image
        run: |
          docker build -f discovery-server/Dockerfile -t sapan18/discovery-server:v1 .

      - name: Push Discovery Server Image
        run: |
          docker push sapan18/discovery-server:v1